version: '3'
services:
  composer:
    image: composer:1.9
    restart: never
    environment:
      - COMPOSER_CACHE_DIR=/app/var/cache/composer
    volumes:
      - .:/app

  phpunit:
    image: php:7.4-cli
    restart: never
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ./vendor/bin/phpunit
